# Generated by Django 2.0.1 on 2018-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.TextField()),
                ('url', models.URLField()),
                ('version_name', models.CharField(max_length=200)),
                ('version_num', models.CharField(max_length=10)),
                ('artist', models.CharField(max_length=200)),
                ('directors', models.CharField(max_length=200)),
                ('release_date_string', models.DateField()),
            ],
        ),
    ]
