version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES _PASSWORD: password
      POSTGRES_DB: muscivideoapp

  node:
    image: "node:8"
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "8000"
    command: "npm start"