version: '3'

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: muscivideoapp