version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: musicvideoapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example

  node:
    image: "node:alpine"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: "npm start"
    depends_on:
      - db